# .github/workflows/_import-single.yml
name: Importar a un Ambiente

on:
  workflow_call:
    inputs:
      release:
        required: true
      environment:
        required: true
      lambdas:
        required: true
        type: boolean
      flows:
        required: true
        type: boolean
      queues:
        required: true
        type: boolean
      users:
        required: true
        type: boolean

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargar ambiente
        id: env
        run: |
          jq -r ".${{ inputs.environment }}" environments.json > env.json
          echo "accountId=$(jq -r '.accountId' env.json)" >> $GITHUB_OUTPUT
          echo "connectInstanceId=$(jq -r '.connectInstanceId' env.json)" >> $GITHUB_OUTPUT

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ steps.env.outputs.accountId }}:role/d3c-GitHubAction-AssumeRoleWithAction
          aws-region: us-east-1

      - name: Importar Lambdas
        if: ${{ inputs.lambdas }}
        env:
          RELEASE_FOLDER: exports/${{ inputs.release }}
        run: python import_lambdas.py

      # ... (flows, queues, users)