name: Importar Release (Simple)

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Nombre del release a importar (ej. release-1.0)'
        required: true
        type: string
      lambdas:
        description: 'Importar Lambdas'
        type: boolean
        default: true
      flows:
        description: 'Importar Flows'
        type: boolean
        default: false
      queues:
        description: 'Importar Queues'
        type: boolean
        default: false
      users:
        description: 'Importar Usuarios'
        type: boolean
        default: false
      target_dev:
        description: 'Importar a DEV'
        type: boolean
        default: true
      target_qa:
        description: 'Después → Importar a QA'
        type: boolean
        default: false
      target_prod:
        description: 'Después → Importar a PROD'
        type: boolean
        default: false

jobs:
  # ==============================
  # 1. IMPORTAR A DEV
  # ==============================
  import-dev:
    if: ${{ inputs.target_dev }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Importar a DEV
        uses: ./.github/workflows/_import-job.yml
        with:
          release: ${{ inputs.release }}
          environment: dev
          lambdas: ${{ inputs.lambdas }}
          flows: ${{ inputs.flows }}
          queues: ${{ inputs.queues }}
          users: ${{ inputs.users }}
        secrets: inherit

  # ==============================
  # 2. ESPERAR APROBACIÓN QA
  # ==============================
  wait-qa:
    if: ${{ inputs.target_qa }}
    needs: import-dev
    runs-on: ubuntu-latest
    steps:
      - name: Esperar aprobación manual
        uses: trstringer/manual-approval@v1
        with:
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          description: '¿Importar a QA?'

  # ==============================
  # 3. IMPORTAR A QA
  # ==============================
  import-qa:
    if: ${{ inputs.target_qa }}
    needs: wait-qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Importar a QA
        uses: ./.github/workflows/_import-job.yml
        with:
          release: ${{ inputs.release }}
          environment: qa
          lambdas: ${{ inputs.lambdas }}
          flows: ${{ inputs.flows }}
          queues: ${{ inputs.queues }}
          users: ${{ inputs.users }}
        secrets: inherit

  # ==============================
  # 4. ESPERAR APROBACIÓN PROD
  # ==============================
  wait-prod:
    if: ${{ inputs.target_prod }}
    needs: import-qa
    runs-on: ubuntu-latest
    steps:
      - name: Esperar aprobación manual
        uses: trstringer/manual-approval@v1
        with:
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          description: '¿Importar a PROD? (¡CUIDADO!)'

  # ==============================
  # 5. IMPORTAR A PROD
  # ==============================
  import-prod:
    if: ${{ inputs.target_prod }}
    needs: wait-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Importar a PROD
        uses: ./.github/workflows/_import-job.yml
        with:
          release: ${{ inputs.release }}
          environment: prod
          lambdas: ${{ inputs.lambdas }}
          flows: ${{ inputs.flows }}
          queues: ${{ inputs.queues }}
          users: ${{ inputs.users }}
        secrets: inherit