name: Obtener Info de Lambda

on:
  workflow_dispatch:  # Ejecutar manualmente

env:
    GITHUB_EXPORT_ROLE: arn:aws:iam::094993749728:role/d3c-GitHubAction-AssumeRole-Connect
    EXPORT_REGION: us-east-1
    GITHUB_IMPORT_ROLE: arn:aws:iam::094993749728:role/d3c-GitHubAction-AssumeRole-Connect
    IMPORT_REGION: us-east-1
    ENVIRONMENT: dev

permissions:
    id-token: write   # Necesario para OIDC
    contents: read

jobs:
  get-lambda-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar boto3
        run: pip install boto3

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GITHUB_EXPORT_ROLE }} # Cambia por tu rol
          aws-region: ${{ env.EXPORT_REGION }}  # Cambia por tu región
          role-session-name: GitHubActionsExport

      - name: Ejecutar script de Lambda
        env:
          LAMBDA_NAME: hl-test  # Cambia por el nombre de tu función
        run: python get_lambda_info.py